#!/bin/bash
# The scripts is written by TranVoSonTung
# The scripts will add more background of the lightdm with the theme "lightdm-webkit2-greeter"
# Dependencies: lightdm, lightdm-webkit2-greeter, lightdm-webkit2-theme-glorious

FLAG="-nopass"
PASS=""

# Use eval "$SUDO_COMMAND <Your command>" to exec the command with no password
SUDO_COMMAND="echo \"$PASS\" | sudo -S -k"

help() {
	echo "This scripts is written by TranVoSonTung"
	echo "Dependencies: lightdm, lightdm-webkit2-greeter, lightdm-webkit2-theme-glorious"
	echo "Usage: $0 [OPTION] [FILE]"
	echo "Add more background to lightdm with the theme \"lightdm-webkit2-greeter\""
	echo "Options:"
	echo "  -nopass     Do not ask for password"
	echo "  -h or --help   Show this help"
	echo "Example:"
	echo "  $0 -nopass backgrounds/1.jpg"
	echo "  $0 backgrounds/1.jpg"
}
# Main code
STOREDDIR="/usr/share/backgrounds/"
PICTURE_ADDING=""

if [ ! -x "$(command -v lightdm)" ]; then
	echo "lightdm is not installed"
	echo "Use add-background-lightdm -h or --help to see help"
	exit 1
fi

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
	help
	exit 0
fi

if [[ "$#" -eq 0 ]]; then
	help
elif [[ "$#" -eq 1 ]]; then
	# no flag
	PICTURE_ADDING=$(readlink -e "$1")
	if [[ -f "$PICTURE_ADDING" ]]; then
		# Make sure that the directory is exist
		sudo mkdir -p "$STOREDDIR"
		sudo cp -i "$PICTURE_ADDING" "$STOREDDIR"
		echo "Add $PICTURE_ADDING to LightDM"
	else
		echo "The picture is not exist"
		echo "Use add-background-lightdm -h or --help to see more information"
	fi
elif [[ "$#" -eq 2 ]]; then
	# use flag
	PICTURE_ADDING=$(readlink -e "$2")
	if [ "$FLAG" = "$1" ]; then
		if [[ -f "$PICTURE_ADDING" ]]; then
			# Make sure that the directory is exist
			eval "$SUDO_COMMAND mkdir -p $STOREDDIR"
			eval "$SUDO_COMMAND cp -i $PICTURE_ADDING $STOREDDIR"
			echo "Add $PICTURE_ADDING to LightDM"
		else
			echo "The picture is not exist"
			echo "Use add-background-lightdm -h or --help to see more information"
		fi
	else
		echo "Usage: $0 [OPTION] [FILE]"
		echo "Use add-background-lightdm -h or --help to see more informations"
	fi
else
	echo "Invalid arguments"
	echo "Usage: $0 [OPTION] [FILE]"
	echo "Use add-background-lightdm -h or --help to see more informations"
fi
