#!/bin/bash
# The scripts is written by TranVoSonTung
# The scripts will add more background of the lightdm with the theme "lightdm-webkit2-greeter"
# Dependencies: lightdm, lightdm-webkit2-greeter, lightdm-webkit2-theme-glorious

FLAG="--nopass"
PASS="STTX300191"

# Use eval "$SUDO_COMMAND <Your command>" to exec the command with no password
SUDO_COMMAND="echo \"$PASS\" | sudo -S -k"

NO='\033[0m' # No Color
BLUE='\033[1;34m'
RED='\033[1;31m'

help() {
	echo -e "${BLUE}INFORMATION:${NO}"
	echo "  This scripts is written by TranVoSonTung"
	echo "  Dependencies: lightdm, lightdm-webkit2-greeter, lightdm-webkit2-theme-glorious"
	echo "  The background will be added to /usr/share/backgrounds/"
	echo "  Add more background to lightdm with the theme \"lightdm-webkit2-greeter\""
	echo -e "\n${BLUE}USAGE:${NO}"
	echo "  add-lightdm-background [OPTION] [FILE]"
	echo -e "\n${BLUE}OPTIONS:${NO}"
	echo "  --nopass     Do not ask for password"
	echo "  -h or --help   Show this help"
	echo -e "\n${BLUE}EXAMPLES:${NO}"
	echo "  add-lightdm-background --nopass backgrounds/1.jpg"
	echo "  add-lightdm-background backgrounds/1.jpg"
}

print_error() {
	echo -e "${RED}[ERROR]: $1${NO}"
}

# Main code
STOREDDIR="/usr/share/backgrounds/"
PICTURE_ADDING=""
CURRENT_DATE=$(date +"%d-%m-%Y_%H-%M-%S")
BACKGROUND_NAME="$STOREDDIR/background_$CURRENT_DATE.png"

if [ ! -x "$(command -v lightdm)" ]; then
	print_error "lightdm is not installed"
	echo "Use add-lightdm-background -h or --help to see help"
	exit 1
fi
if [[ "$#" -eq 0 ]]; then
	help
	exit 0
elif [[ "$#" -eq 1 ]]; then
	if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
		help
		exit 0
	else
		# no flag
		PICTURE_ADDING=$(readlink -e "$1")
		if [[ -f "$PICTURE_ADDING" ]]; then
			# Make sure that the directory is exist
			sudo mkdir -p "$STOREDDIR"
			sudo cp -i "$PICTURE_ADDING" "$BACKGROUND_NAME"
			echo "Add $PICTURE_ADDING to LightDM"
		else
			print_error "The picture is not exist"
			echo "Use add-lightdm-background -h or --help to see more information"
		fi
	fi

elif [[ "$#" -eq 2 ]]; then
	# use flag
	PICTURE_ADDING=$(readlink -e "$2")
	if [ "$FLAG" = "$1" ]; then
		if [[ -f "$PICTURE_ADDING" ]]; then
			# Make sure that the directory is exist
			eval "$SUDO_COMMAND mkdir -p $STOREDDIR"
			eval "$SUDO_COMMAND cp -i $PICTURE_ADDING $BACKGROUND_NAME"
			echo "Add $PICTURE_ADDING to LightDM"
		else
			print_error "The picture is not exist"
			echo "Use add-lightdm-background -h or --help to see more information"
		fi
	else
		echo "Usage: add-lightdm-background [OPTION] [FILE]"
		echo "Use add-lightdm-background -h or --help to see more information"
	fi
else
	print_error "Invalid arguments"
	echo "Usage: add-lightdm-background [OPTION] [FILE]"
	echo "Use add-lightdm-background -h or --help to see more information"
fi
