#!/bin/bash
# This scripts is written by Tran Vo Son Tung
# This scripts is used to add more background to LightDM

STOREDDIR="/usr/share/backgrounds/"
PICTURE_ADDING=$(readlink -e "$1")
PASS=""

if [[ ! -d "$STOREDDIR" ]]; then
	echo "$PASS" | sudo -S -k mkdir "$STOREDDIR"
	echo -e '\n'
	echo "Created $STOREDDIR"
fi

if [[ "$#" -eq 1 ]]; then
	if [[ -f "$PICTURE_ADDING" ]]; then
		echo "$PASS" | sudo -S -k cp -i "$PICTURE_ADDING" "$STOREDDIR"
		echo -e '\n'
		echo "Add $PICTURE_ADDING to LightDM"
	else
		echo "The picture is not exist"
	fi
else
	echo "Usage: $0 <picture>"
	echo "Example: $0 ~/Pictures/1.jpg"
fi
