#!/bin/bash
STOREDDIR="/usr/share/backgrounds/"
PASS="STTX300191"
PICTURETOCHANGE=$(readlink -e "$1")

if [[ ! -d "$STOREDDIR" ]]; then
	echo "$PASS" | sudo -S -k mkdir "$STOREDDIR"
	echo -e '\n'
	echo "Created $STOREDDIR"
fi

if [[ "$#" -eq 1 ]]; then
	if [[ -f "$PICTURETOCHANGE" ]]; then
		echo "$PASS" | sudo -S -k cp -i "$PICTURETOCHANGE" "$STOREDDIR"
		echo -e '\n'
		echo "Add $PICTURETOCHANGE to LightDM"
	else
		echo "The picture is not exist"
	fi
else
	echo "Only one variable is allowed"
fi
