#!/bin/bash

intern="eDP-1"
extern=$2
if [ -z "$extern" ]; then
	extern="HDMI-1"
fi
resolution=$3
if [ -z "$resolution" ]; then
	resolution="1920x1080"
fi

case "$1" in
"disconnect")
	xrandr --output "$extern" --off --output $intern --auto
	;;
"right")
	xrandr --output "$extern" --set audio force-dvi --mode "$resolution" && xrandr --output $intern --auto --output "$extern" --right-of $intern
	;;
"left")
	xrandr --output "$extern" --set audio force-dvi --mode "$resolution" && xrandr --output $intern --auto --output "$extern" --left-of $intern
	;;
"above")
	xrandr --output "$extern" --set audio force-dvi --mode "$resolution" && xrandr --output $intern --auto --output "$extern" --above $intern
	;;
"below")
	xrandr --output "$extern" --set audio force-dvi --mode "$resolution" && xrandr --output $intern --auto --output "$extern" --below $intern
	;;
"mirror")
	xrandr --output "$extern" --set audio force-dvi --mode "$resolution" && xrandr --output $intern --auto --output "$extern" --same-as $intern
	;;
*)
	echo "Usage: $0 {disconnect|right|left|above|below|mirror}"
	exit 1
	;;
esac
