#!/bin/bash
# The scripts is written by TranVoSonTung
# The scripts will change the avatar of the lightdm with the theme "lightdm-webkit2-greeter wget"
# Dependencies: lightdm, lightdm-webkit2-greeter, lightdm-webkit2-theme-glorious

FLAG="-nopass"
PASS=""

# Use eval "$SUDO_COMMAND <Your command>" to exec the command with no password
SUDO_COMMAND="echo \"$PASS\" | sudo -S -k"

USERNAME=$(whoami)
AVATARSTOREDPATH="/var/lib/AccountsService/icons/$USERNAME"
STOREDDIR=/var/lib/AccountsService/icons
AVATAR=""

# main code
if [ -x "$(command -v lightdm)" ]; then
	if [[ ! -d "$STOREDDIR" ]]; then
		if [ "$FLAG" = "$1" ] && [ "$PASS" != "" ]; then
			eval "$SUDO_COMMAND mkdir $STOREDDIR"
		else
			sudo mkdir "$STOREDDIR"
		fi
		clear
		echo "Create $STOREDDIR"
	fi

	# Change avatar
	if [[ "$#" -eq 2 ]]; then
		# Have the flag
		# The flag must be the first parameter
		if [[ "$1" == "$FLAG" ]]; then
			AVATAR=$(readlink -e "$2")
			if [[ -f "$AVATAR" ]]; then
				eval "$SUDO_COMMAND cp $AVATAR $AVATARSTOREDPATH"
				echo -e "\n"
				echo "Change the avatar to $AVATAR"
			else
				echo "The picture path is not exist"
			fi
		else
			echo "Syntax error"
			echo "The syntax form: setavatar.st -nopass <picuter-path>"
		fi
	elif [[ "$#" -eq 1 ]]; then
		# No flag
		AVATAR=$(readlink -e "$1")
		if [[ -f "$AVATAR" ]]; then
			sudo cp "$AVATAR" "$AVATARSTOREDPATH"
			echo -e "\n"
			echo "Changed the avatar to $AVATAR"
		else
			echo "The picture path is not exist"
		fi
	else
		echo "Syntax error"
		echo "The syntax form: setavatar.st -nopass <picuter-path> or setavatar.st <picture-path>"
	fi
else
	echo "You need to installed lightdm"
	# Ask to install lightdm
	echo "Do you want to install lightdm? (y/n)"
	read -r answer
	if [[ "$answer" == "y" ]]; then
		echo "Installing lightdm, lightdm-webkit2-greeter..."
		sudo pacman -S lightdm lightdm-webkit2-greeter

		# Check if installed lightdm, enable service
		if [ -x "$(command -v lightdm)" ]; then
			sudo systemctl enable lightdm.service
		fi

		echo "Installing lightdm-webkit2-theme-glorious..."
		yay -S lightdm-webkit2-theme-glorious

		# Set default lightdm greeter to lightdm-webkit2-greeter
		sudo sed -i -e "s/^#greeter-session\s*=\s*\(.*\)/greeter-session=lightdm-webkit2-greeter/g" "/etc/lightdm/lightdm.conf"
		# Set default lightdm-webkit2-greeter theme to Glorious
		sudo sed -i -e "s/^webkit_theme\s*=\s*\(.*\)/webkit_theme = glorious/g" "/etc/lightdm/lightdm-webkit2-greeter.conf"
		sudo sed -i -e "s/^debug_mode\s*=\s*\(.*\)/debug_mode = true/g" "/etc/lightdm/lightdm-webkit2-greeter.conf"
	fi
fi
