#!/bin/bash
# This scripts is wtitten by Tran Vo Son Tung
# This script is used to change the wallpaper of i3wm
# Dependencies: feh, i3wm
# Usage: setwallpaper <path_to_image>

help() {
	echo "This scripts is wtitten by Tran Vo Son Tung"
	echo "This script is used to change the wallpaper of i3wm"
	echo "Dependencies: feh, i3wm"
	echo "Usage: setwallpaper <path_to_image>"
	echo "Example: setwallpaper ~/Pictures/wallpaper.jpg"
}

# Check if install feh
if [ ! -x "$(command -v feh)" ]; then
	echo "Please install feh to use this scripts"
	exit 1
fi

# Check if install i3wm
if [ ! -x "$(command -v i3)" ]; then
	echo "You don't use i3wm"
	echo "Please install i3wm to use this scripts, or you can customize this scripts to use with your window manager"
	exit 1
fi

# Main code
# Make sure the wallpaper directory exists
mkdir -p ~/.config/background

if [[ "$#" -eq 0 ]]; then
	help
elif [[ "$#" -eq 1 ]] && [[ "$1" == "-h" ]]; then
	help
elif [[ "$#" -eq 1 ]] && [[ "$1" == "--help" ]]; then
	help
elif [[ "$#" -eq 1 ]]; then
	if cat "$HOME/.config/i3/config" | tr "," "\n" | grep -xqF "set $wallpaper ~/.config/background/wallpaper.jpg"; then
		# Check if the path is correct
		if [[ ! -f "$1" ]]; then
			echo "Error: Invalid path"
			exit 1
		fi
		cp "$1" ~/.config/background/wallpaper.jpg && i3 restart
	else
		echo "Error: Wallpaper is not set in i3 config"
		echo "Please add the following line to your i3 config file"
		echo "set $wallpaper ~/.config/background/wallpaper.jpg"
		echo "exec_always feh --bg-fill $wallpaper"
		echo "remove your other lines that you use to set wallpaper in your i3 config file to use this scripts"
		exit 1
	fi
else
	echo "Error: Invalid number of arguments"
	echo "Usage: setwallpaper <path_to_image>"
	echo "Use -h or --help for help"
fi
