#!/bin/bash
# This scripts is wtitten by Tran Vo Son Tung
# This script is used to change the wallpaper of i3wm
# Dependencies: feh, i3wm
# Usage: setwallpaper <path_to_image>

# Colors
NO='\033[0m' # No Color
BLUE='\033[1;34m'
RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'

display_help() {
	echo -e "${BLUE}INFORMATION:${NO}"
	echo -e "  This script is written by Tran Vo Son Tung"
	echo -e "  This script is used to change the wallpaper of i3wm"
	echo -e "  Dependencies: feh, i3wm"

	echo -e "\n${BLUE}USAGE:${NO} setwallpaper [OPTIONS] [IMAGE_PATH]"

	echo -e "\n${BLUE}OPTIONS:${NO}"
	echo -e "  -h, --help         show help"

	echo -e "\n${BLUE}EXAMPLES:${NO}"
	echo -e "  setwallpaper --help"
	echo -e "  setwallpaper ~/Pictures/wallpaper.jpg"
}

display_warning() {
	echo -e "${YELLOW}WARNING:${NO} $1"
	introduce_help
}

introduce_help() {
	echo -e "${BLUE}MORE:${NO}Use ldoc-custom --help or ldoc-custom -h to get more information"
}

display_error() {
	echo -e "${RED}ERROR:${NO} $1"
	introduce_help
	exit 1
}

# Check if install feh
if [ ! -x "$(command -v feh)" ]; then
	display_error "feh is not installed, please install feh to use this scripts"
fi

# Check if install i3wm
if [ ! -x "$(command -v i3)" ]; then
	display_error "i3wm is not installed, please install i3wm to use this scripts"
fi

# Main code
# Show help if no arguments
if [[ "$#" -eq 0 ]]; then
	display_help
	exit 0
fi

# Show help if -h or --help is passed
if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
	display_help
	exit 0
fi

WALLPAPER_STORAGE_DIR="$HOME/.config/wallpaper"

if [[ "$#" -eq 1 ]]; then
	if cat "$HOME/.config/i3/config" | tr "," "\n" | grep -xqF "set \$wallpaper ~/.config/wallpaper/wallpaper.jpg"; then
		# Check if the path is correct
		if [[ ! -f "$1" ]]; then
			display_error "Invalid path"
		fi
		# Make sure the wallpaper directory exists
		mkdir -p "$WALLPAPER_STORAGE_DIR"
		cp "$1" "$WALLPAPER_STORAGE_DIR/wallpaper.jpg" && i3 restart && [ -x "$(command -v dunstify)" ] && dunstify "Wallpaper changed" -i "$1" -a "setwallpaper-script"
	else
		echo -e "${RED} ERROR: ${NO} Wallpaper is not set in i3 config"
		echo -e "${GREEN} SOME HINTS: ${NO}"
		echo "Please add two following lines to your i3 config file"
		echo "set \$wallpaper ~/.config/wallpaper/wallpaper.jpg"
		echo "exec_always feh --bg-fill \$wallpaper"
		echo "Remove your other lines that you use to set wallpaper in your i3 config file to use this scripts"
		exit 0
	fi
else
	display_error "Invalid number of arguments"
fi
