#!/usr/bin/env sh
# George Ornbo (shapeshed) http://shapeshed.com
# License - http://unlicense.org


# Fixes a corrupt .zsh_history file

help() {
  echo "This script is written by George Ornbo (shapeshed) http://shapeshed.com"
  echo "This script fixes a corrupt .zsh_history file"
  exit 1
}

if [ "$1" == "-h" ] ; then
  help
  exit 1
elif [ "$1" == "--help" ] ; then
  help
  exit 1
fi

mv ~/.zsh_history ~/.zsh_history_bad
strings .zsh_history_bad > .zsh_history
fc -R ~/.zsh_history
rm ~/.zsh_history_bad

